### ISSUE TITLE
error while loading shared libraries: libatomic.so.1

### ISSUE THREAD

**Issue by kyouko-taiga** [cui-unige/outils-formels-modelisation-2018#39]
Some of you stumbled on this problem while trying to install/run swift:

```
error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

This is due to a missing dependency on your system, which you should be able to install with the following command:

```bash
apt-get install libatomic1
```

For later references, when your Ubuntu system complains about a missing sharing library, you can use [this website](https://packages.ubuntu.com) to search which package to install to get said library.

**Comment by MohannadEhabBarakat** [comment]
saved my day @kyouko-taiga

**Comment by dev-markus** [comment]
Hey thanks a lot! Have fix my error with ssh connect:
Visual Studio Code - Plugin: "ssh remote"
Trying to connect to Local Ubuntu Server (Ruspberry)

**Comment by zhengjiacheng123** [comment]
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`
