### ISSUE TITLE
error while loading shared libraries: libatomic.so.1: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by DenizSungurtekin** [cui-unige/outils-formels-modelisation-2018#44]
Quand on a ça on tape ce qui suit dans la commande:
**atom ~/.profile**
Normalement y a une page atom qui s'ouvre et on y écrit à la fin  export PATH=~/[Emplacement du dossier swift-4.2]/usr/bin/:"${PATH}" 

Exemple pour moi j'ai tapé :export PATH=~/Téléchargements/swift-4.2-RELEASE-ubuntu18.04/usr/bin/:"${PATH}"

**Comment by LukeAndrewSmith** [comment]
Magnifique

**Comment by DenizSungurtekin** [comment]
Merci c'était vraiment éprouvant à faire mais c'est bon.
