### ISSUE TITLE
Comment "return" un objet de type Marking?

### ISSUE THREAD

**Issue by yassinhediger** [cui-unige/outils-formels-modelisation-2018#53]
Même après avoir regardé le GitHub de PetriKit, je n'arrive pas a trouver la doc présentant la syntaxe des objets de type Marking. 

Merci

**Comment by immortal79** [comment]
C'est parce que ce n'est pas un objet, c'est une fonction (Place) -> Nat donc dans ta méthode qui retourne un marking tu dois retourner qqch du genre:
`return {
(place) -> Nat in
var unNat: Nat!
//écrire le code ici
return unNat
}`
